### ISSUE TITLE
Image Issues/Gripes/Suggestions

### ISSUE THREAD

**Issue by MDFL64** [sirsavary/modmountain-issues#23]
Enforcing 5-6 images per addon is pretty crazy IMO. Sorry for listing so many points in one issue, I just have a lot of gripes with the current system, and most of them are interrelated.
1. Both card images _still_ list the same dimensions. Consider only using one card image?
2. Card image dimensions are absurdly large.
3. Consider removing image dimension requirements on preview images.
4. Require a minimum of 1 preview image. No maximum (I have not tested if this is already the case)

**Comment by sirsavary** [comment]
1. My bad, fixing.
2. Yeah I just initially set them to what the CSS framework came with. I'll do some experimenting and find a better resolution / aspect ratio.
3. You mean the gallery images? They need to be square, preferably. Maybe I could split it into "highlight images" that show on the little slider, and then add a media page that accepts images of any size.
4. The maximum is more so because of looks / styling on the store page. I'll try supplying less and see how it looks.

**Comment by sirsavary** [comment]
Made some modifications to image handling. Try it out and let me know what you think.
